# Day-1 for practicing Numpy
  Start with basic

In [1]:
import numpy as np

### Making array from list

In [2]:
arr_1=np.array([1,2,3,4,5,6])
print("Array-1:",arr_1)
arr_2=np.array([[1,2,3],[4,5,6]])
print("Array-2:",arr_2)

Array-1: [1 2 3 4 5 6]
Array-2: [[1 2 3]
 [4 5 6]]


### List VS numpy Array

In [3]:
List=[1,2,3,4,5,6]
print("Multiplication of list:",List*2)
np_array=np.array([1,2,3,4,5,6])
print("Multiplication of numpy array:",np_array*2)

Multiplication of list: [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]
Multiplication of numpy array: [ 2  4  6  8 10 12]


### Zeros , ones , random , full , sequence

In [4]:
Zeros=np.zeros((2,2))
print("Zero matrix: \n",Zeros)
Ones=np.ones((5,5))
print("One matrix: \n",Ones)
Full=np.full((4,4),7)
print("Full matrix: \n",Full)
Random=np.random.random((3,3))
print("Random Matrix:\n",Random)
Sequence=np.arange(0,11,2)
print("Sequence:\n",Sequence)


Zero matrix: 
 [[0. 0.]
 [0. 0.]]
One matrix: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full matrix: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Random Matrix:
 [[0.26479806 0.80456986 0.72103928]
 [0.45417019 0.00399713 0.85405114]
 [0.15868244 0.52873109 0.97730241]]
Sequence:
 [ 0  2  4  6  8 10]


### Vector,Matrix and Tensor

In [5]:
Vector=np.array([1,2,3,4,5,6])
print("Vector:\n",Vector)
Matrix=np.array([[1,2,3],[4,5,6]])
print("Matrix:\n",Matrix)
Tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor:\n",Tensor)

Vector:
 [1 2 3 4 5 6]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Property

In [6]:
arr=np.array([[1,2,3],
             [4,5,6]])
print("Array Shape:",arr.shape)
print("Array Dimension:",arr.ndim)
print("Array Size:",arr.size)
print("Array Datatype:",arr.dtype)
print("Array Base",arr.base)
print("Array Data",arr.data)

Array Shape: (2, 3)
Array Dimension: 2
Array Size: 6
Array Datatype: int64
Array Base None
Array Data <memory at 0x0000025397776740>


### Manipulation of size of array

In [7]:
ex=np.arange(0,12)
print("original Matrix:\n",ex)
Reshaped=ex.reshape((2,6))
print("Reshaped Matrix:\n",Reshaped)
Falltened=Reshaped.flatten()
print("Flattened Matrix:\n",Falltened)
Ravel=Reshaped.ravel()
print("Ravel Matrix:\n",Ravel)
Transpose=Reshaped.T
print("Transpose Matrix:\n",Transpose)

original Matrix:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Matrix:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened Matrix:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel Matrix:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose Matrix:
 [[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


## That the day off